version: 2.1

defaults: &defaults
  working_directory: /tmp/app
  docker:
    - image: cimg/base:2024.12

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container image
          command: |
            docker build /tmp/app -f Containerfile -t ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
            docker build /tmp/app -f Containerfile -t ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:latest
            docker image ls
      - run:
          name: Maybe publish container image
          command: |
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            docker push ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
            docker push ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:latest

workflows:
  version: 2
  main:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
